version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: rbac-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-rbac_db}
    ports:
      - "${DB_PORT:-5433}:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
